// Code generated by compgen
package components

import (
    "github.com/google/uuid"
    "github.com/lijianying10/GoRender/pkg/render"
)

// Render component Render
func (list *ListTODOItems) Render(tid string) string {
    list.AppendRenderTraceID(tid)
    return list.render(tid)
}

// Destructor Comp DoDestructor
func (list *ListTODOItems) Destructor() {
    for _, comp := range list.SubComponents {
        comp.Destructor()
    }
    list.destructor()
}

// Constructor Comp DoDestructor
func (list *ListTODOItems) Constructor(grender *render.GoRender) {
    list.Runtime = grender
    list.UUID = uuid.New().String()
    list.constructor()
}
