// Code generated by compgen
package components

import (
    "github.com/google/uuid"
    "github.com/lijianying10/GoRender/pkg/render"
)

// Render component Render
func (item *ListTODOItem) Render(tid string) string {
    item.AppendRenderTraceID(tid)
    return item.render(tid)
}

// Destructor Comp DoDestructor
func (item *ListTODOItem) Destructor() {
    for _, comp := range item.SubComponents {
        comp.Destructor()
    }
    item.destructor()
}

// Constructor Comp DoDestructor
func (item *ListTODOItem) Constructor(grender *render.GoRender) {
    item.Runtime = grender
    item.UUID = uuid.New().String()
    item.constructor()
}
